---
apiVersion: v1
kind: Service
metadata:
  name: aws-otel-collector-service
  namespace: aws-otel-collector
spec:
  selector:
    app: aws-otel-collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
---