apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - ../base
  - kafka-persistent-single.yaml #"https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml"

# patches:
#   - target:
#       group: kafka.strimzi.io
#       version: v1beta2
#       kind: Kafka
#       name: my-cluster
#     patch: |-
#       - op: replace
#         path: /metadata/name
#         value: dev-cluster
---


