receivers:
  # Receives traces from the instrumented application
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 # export OTEL_EXPORTER_OTLP_ENDPOINT=<host:port> or use the default 0.0.0.0:4317

exporters:
  logging:
    verbosity: detailed
  # Exports to jaeger for visualization
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    tls:
      insecure: true
  # Exports to ADOT collector
  otlp:
    endpoint: "adot-collector:55681"  # Use the service name of the ADOT collector defined in the Docker Compose file.
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,otlp,jaeger]


